"""Kotlin-only regression fixtures adapted from qmix's erosion tests."""
# Adapted from leugenea/qmix at 0cc3f1eb8bfb1902ac8e2fae7fba729ef53cc9f0.
# Copyright (c) 2026 QMix contributors; MIT License (see LICENSE in this directory).
import json
import math
import os
import pathlib
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

import erosion

SCRIPT = pathlib.Path(__file__).with_name("erosion.py")


class ErosionTest(unittest.TestCase):
    def test_unreadable_in_scope_header_reports_file_and_line(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            source = root / "app/src/main/java/Unreadable.kt"
            source.parent.mkdir(parents=True)
            source.write_text("fun f() = 1\n")
            with mock.patch.object(pathlib.Path, "open", side_effect=OSError("denied")):
                with self.assertRaisesRegex(ValueError, r"Unreadable.kt:1: cannot read source header"):
                    erosion.discover_sources(root)

    def test_kotlin_declaration_only_scope_has_zero_mass_without_failure(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            source = root / "app/src/main/java/Contract.kt"
            source.parent.mkdir(parents=True)
            source.write_text("interface Contract {\n fun invoke(): Unit\n}\n")
            report = erosion.analyze(root)
            self.assertEqual(report["languages"]["Kotlin"]["function_count"], 0)
            self.assertEqual(report["languages"]["Kotlin"]["files_selected"], 1)
            self.assertEqual(report["languages"]["Kotlin"]["files_with_functions"], 0)
            self.assertEqual(report["languages"]["Kotlin"]["erosion"], 0)

    def test_kotlin_parse_error_aborts_report_with_file_and_line(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            source = root / "app/src/main/java/Broken.kt"
            source.parent.mkdir(parents=True)
            source.write_text("fun broken() {\n    if (\n}\n")
            with self.assertRaisesRegex(ValueError, r"Broken.kt:[1-3]: Kotlin parse error"):
                erosion.analyze(root)

    def test_weighted_erosion_strict_threshold(self):
        rows = [{"file": "app/src/main/A.kt", "function": name, "language": "Kotlin",
                 "ccn": ccn, "nloc": nloc, "mass": ccn * math.sqrt(nloc)}
                for name, ccn, nloc in (("low", 10, 4), ("high", 11, 9))]
        report = erosion.calculate(rows)
        self.assertEqual(report["schema_version"], 2)
        self.assertEqual(set(report["languages"]), {"Kotlin"})
        self.assertEqual(report["languages"]["Kotlin"]["high_ccn_count"], 1)
        self.assertAlmostEqual(report["languages"]["Kotlin"]["erosion"], 33 / 53)
        self.assertEqual(report["functions"][1]["mass"], 33)

    def test_excludes_tests_generated_build_and_vendored_sources(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            files = {"app/src/main/java/App.kt": "fun app() {}\n"}
            for name in ("app/src/test/Test.kt", "app/src/androidTest/Test.kt",
                         "app/src/main/java/AppTest.kt", "app/src/main/tests/X.kt",
                         "app/src/main/generated/G.kt", "app/src/main/build/B.kt",
                         "app/src/main/third_party/V.kt", "app/src/main/vendor/V.kt",
                         "app/src/main/java/X.generated.kt", "app/src/main/java/X_generated.kt"):
                files[name] = "fun excluded() {}\n"
            files["app/src/main/java/Generated.kt"] = "// Code generated by a tool. DO NOT EDIT.\nfun generated() {}\n"
            for path, content in files.items():
                dest = root / path
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(content)
            self.assertEqual(erosion.discover_sources(root), ["app/src/main/java/App.kt"])

    def test_empty_aggregate_is_zero_but_missing_corpus_is_an_error(self):
        report = erosion.calculate([])
        self.assertEqual(report["languages"]["Kotlin"]["erosion"], 0)
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            with self.assertRaisesRegex(ValueError, "missing production"):
                erosion.analyze(root)
            (root / "app/src/main").mkdir(parents=True)
            with self.assertRaisesRegex(ValueError, "no production"):
                erosion.analyze(root)

    def test_unreadable_directory_aborts_discovery(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            (root / "app/src/main").mkdir(parents=True)
            def broken_walk(base, onerror):
                onerror(PermissionError(13, "denied", str(base)))
                return iter(())
            with mock.patch.object(os, "walk", side_effect=broken_walk):
                with self.assertRaisesRegex(ValueError, "cannot discover"):
                    erosion.discover_sources(root)

    def test_top_five_sorted_and_markdown_escaped(self):
        rows = [{"file": "app/src/main/A.kt", "function": f"<f{i}>|x", "language": "Kotlin",
                 "ccn": i, "nloc": 4, "mass": i * 2} for i in range(1, 8)]
        report = erosion.calculate(rows)
        self.assertEqual([row["ccn"] for row in report["top_five"]["Kotlin"]], [7, 6, 5, 4, 3])
        body = erosion.render_markdown(report)
        self.assertEqual(body.count("<!-- code-erosion -->"), 1)
        self.assertIn("&lt;f7&gt;\\|x", body)
        self.assertIn("Functions with CCN > 10", body)
        self.assertEqual(json.loads(json.dumps(report))["languages"], report["languages"])

    def test_cli_writes_current_source_json_and_matching_summary(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            path = root / "app/src/main/A.kt"
            path.parent.mkdir(parents=True)
            path.write_text("fun branch() = if (true) 1 else 0\n")
            output, summary = root / "report.json", root / "report.md"
            subprocess.run([sys.executable, str(SCRIPT), "--repo", str(root),
                            "--output", str(output), "--summary", str(summary)], check=True)
            report = json.loads(output.read_text())
            self.assertEqual(report["functions"][0]["ccn"], 2)
            self.assertEqual(report["languages"]["Kotlin"]["files_selected"], 1)
            self.assertEqual(summary.read_text(), erosion.render_markdown(report))


if __name__ == "__main__":
    unittest.main()
