package io.github.leugenea.codexbarmobile

import io.github.leugenea.codexbarmobile.history.*
import io.github.leugenea.codexbarmobile.usage.*
import io.github.leugenea.codexbarmobile.transport.ReadError

/** Exhaustive resource inventory: native tests verify every declared state has a label. */
internal fun historyStateResource(state: Enum<*>): Int = historyStateResources.getValue(state)

internal val historyStateResources: Map<Enum<*>, Int> = mapOf(
    HistoryReadiness.UNAVAILABLE to R.string.history_state_historyreadiness_unavailable,
    HistoryReadiness.LOADING to R.string.history_state_historyreadiness_loading,
    HistoryReadiness.EMPTY to R.string.history_state_historyreadiness_empty,
    HistoryReadiness.READY to R.string.history_state_historyreadiness_ready,
    HistoryReadiness.ERROR to R.string.history_state_historyreadiness_error,
    HistoryPlotContent.NO_PAGE to R.string.history_state_historyplotcontent_no_page,
    HistoryPlotContent.EMPTY_PAGE to R.string.history_state_historyplotcontent_empty_page,
    HistoryPlotContent.FILTERED_EMPTY to R.string.history_state_historyplotcontent_filtered_empty,
    HistoryPlotContent.STATUS_ONLY to R.string.history_state_historyplotcontent_status_only,
    HistoryPlotContent.SINGLE_POINT to R.string.history_state_historyplotcontent_single_point,
    HistoryPlotContent.MULTIPLE_POINTS to R.string.history_state_historyplotcontent_multiple_points,
    WindowKind.FIVE_HOUR to R.string.history_state_windowkind_five_hour,
    WindowKind.WEEKLY to R.string.history_state_windowkind_weekly,
    WindowKind.UNSUPPORTED to R.string.history_state_windowkind_unsupported,
    WindowKind.UNKNOWN to R.string.history_state_windowkind_unknown,
    Knowledge.KNOWN to R.string.history_state_knowledge_known,
    Knowledge.UNAVAILABLE to R.string.history_state_knowledge_unavailable,
    Knowledge.MALFORMED to R.string.history_state_knowledge_malformed,
    Knowledge.UNSUPPORTED to R.string.history_state_knowledge_unsupported,
    Reason.MISSING to R.string.history_state_reason_missing,
    Reason.PROVIDER_NULL to R.string.history_state_reason_provider_null,
    Reason.WRONG_TYPE to R.string.history_state_reason_wrong_type,
    Reason.OUT_OF_RANGE to R.string.history_state_reason_out_of_range,
    Reason.UNSUPPORTED_FORMAT to R.string.history_state_reason_unsupported_format,
    Reason.CLOCK_REQUIRED to R.string.history_state_reason_clock_required,
    SelectionState.KNOWN to R.string.history_state_selectionstate_known,
    SelectionState.UNAVAILABLE to R.string.history_state_selectionstate_unavailable,
    SelectionState.MALFORMED to R.string.history_state_selectionstate_malformed,
    SelectionState.AMBIGUOUS to R.string.history_state_selectionstate_ambiguous,
    Slot.PRIMARY to R.string.history_state_slot_primary,
    Slot.SECONDARY to R.string.history_state_slot_secondary,
    ResetProvenance.ABSOLUTE to R.string.history_state_resetprovenance_absolute,
    ResetProvenance.RELATIVE_DERIVED to R.string.history_state_resetprovenance_relative_derived,
    ResetProvenance.UNKNOWN to R.string.history_state_resetprovenance_unknown,
    ResetProvenance.AMBIGUOUS to R.string.history_state_resetprovenance_ambiguous,
    ResetProvenance.MALFORMED to R.string.history_state_resetprovenance_malformed,
    ResetProvenance.UNSUPPORTED to R.string.history_state_resetprovenance_unsupported,
    ResetProvenance.DISCREPANT to R.string.history_state_resetprovenance_discrepant,
    NominalStartConfidence.NOMINAL_FULL_QUOTA to R.string.history_state_nominalstartconfidence_nominal_full_quota,
    NominalStartConfidence.UNCERTAIN_CORRECTION to R.string.history_state_nominalstartconfidence_uncertain_correction,
    NominalStartConfidence.UNAVAILABLE to R.string.history_state_nominalstartconfidence_unavailable,
    BaselineEligibility.ELIGIBLE to R.string.history_state_baselineeligibility_eligible,
    BaselineEligibility.UNKNOWN_OBSERVATION_TIME to R.string.history_state_baselineeligibility_unknown_observation_time,
    BaselineEligibility.WINDOW_UNAVAILABLE to R.string.history_state_baselineeligibility_window_unavailable,
    BaselineEligibility.AMBIGUOUS_WINDOW to R.string.history_state_baselineeligibility_ambiguous_window,
    BaselineEligibility.UNKNOWN_PERCENT to R.string.history_state_baselineeligibility_unknown_percent,
    BaselineEligibility.UNKEYED_RESET to R.string.history_state_baselineeligibility_unkeyed_reset,
    BaselineEligibility.BEFORE_NOMINAL_START to R.string.history_state_baselineeligibility_before_nominal_start,
    BaselineEligibility.AFTER_RESET to R.string.history_state_baselineeligibility_after_reset,
    BaselineEligibility.CLOCK_UNVERIFIED to R.string.history_state_baselineeligibility_clock_unverified,
    BaselineEligibility.CLOCK_DISCONTINUITY to R.string.history_state_baselineeligibility_clock_discontinuity,
    BaselineEligibility.UNCERTAIN_CORRECTION to R.string.history_state_baselineeligibility_uncertain_correction,
    BaselineEligibility.TIME_RANGE_OVERFLOW to R.string.history_state_baselineeligibility_time_range_overflow,
    ResetCause.UNKNOWN to R.string.history_state_resetcause_unknown,
    BreakReason.FIRST_OBSERVATION to R.string.history_state_breakreason_first_observation,
    BreakReason.WINDOW_CHANGED to R.string.history_state_breakreason_window_changed,
    BreakReason.PERCENT_CORRECTION to R.string.history_state_breakreason_percent_correction,
    BreakReason.BACKGROUND to R.string.history_state_breakreason_background,
    BreakReason.READ_ERROR to R.string.history_state_breakreason_read_error,
    BreakReason.FIELD_GAP to R.string.history_state_breakreason_field_gap,
    BreakReason.AMBIGUOUS_WINDOW to R.string.history_state_breakreason_ambiguous_window,
    BreakReason.UNKEYED_RESET to R.string.history_state_breakreason_unkeyed_reset,
    BreakReason.UNKNOWN_OBSERVATION_TIME to R.string.history_state_breakreason_unknown_observation_time,
    BreakReason.INTERVAL_EXCEEDED to R.string.history_state_breakreason_interval_exceeded,
    BreakReason.NON_INCREASING_WALL_TIME to R.string.history_state_breakreason_non_increasing_wall_time,
    BreakReason.MONOTONIC_UNAVAILABLE to R.string.history_state_breakreason_monotonic_unavailable,
    BreakReason.NON_INCREASING_MONOTONIC_TIME to R.string.history_state_breakreason_non_increasing_monotonic_time,
    BreakReason.WALL_MONOTONIC_DIVERGENCE to R.string.history_state_breakreason_wall_monotonic_divergence,
    BreakReason.NEW_CLOCK_EPOCH to R.string.history_state_breakreason_new_clock_epoch,
    HistoryGap.BACKGROUND to R.string.history_state_historygap_background,
    HistoryGap.READ_ERROR to R.string.history_state_historygap_read_error,
    HistoryTruncation.AGE_RETENTION to R.string.history_state_historytruncation_age_retention,
    HistoryTruncation.OBSERVATION_CAP to R.string.history_state_historytruncation_observation_cap,
    HistoryTruncation.BYTE_CAP to R.string.history_state_historytruncation_byte_cap,
    HistoryRecorderProblem.STORAGE_UNAVAILABLE to R.string.history_state_historyrecorderproblem_storage_unavailable,
    HistoryRecorderProblem.READ_FAILURE to R.string.history_state_historyrecorderproblem_read_failure,
    HistoryRecorderProblem.WRITE_FAILURE to R.string.history_state_historyrecorderproblem_write_failure,
    HistoryRecorderProblem.CORRUPT to R.string.history_state_historyrecorderproblem_corrupt,
    HistoryRecorderProblem.QUEUE_OVERFLOW to R.string.history_state_historyrecorderproblem_queue_overflow,
    HistoryRecorderProblem.ORDINAL_CAPACITY to R.string.history_state_historyrecorderproblem_ordinal_capacity,
    HistoryUnavailable.IO_FAILURE to R.string.history_state_historyunavailable_io_failure,
    HistoryUnavailable.CLOSED to R.string.history_state_historyunavailable_closed,
    HistoryUnavailable.PARTITION_REVOKED to R.string.history_state_historyunavailable_partition_revoked,
    HistoryUnavailable.CAPACITY to R.string.history_state_historyunavailable_capacity,
    HistoryUnavailable.READ_FAILURE to R.string.history_state_historyunavailable_read_failure,
    HistoryUnavailable.WRITE_FAILURE to R.string.history_state_historyunavailable_write_failure,
    HistoryUnavailable.STORAGE_FULL to R.string.history_state_historyunavailable_storage_full,
    HistoryUnavailable.UNSUPPORTED_SCHEMA to R.string.history_state_historyunavailable_unsupported_schema,
    ReadError.REAUTHORIZE to R.string.history_state_readerror_reauthorize,
    ReadError.FORBIDDEN to R.string.history_state_readerror_forbidden,
    ReadError.RATE_LIMITED to R.string.history_state_readerror_rate_limited,
    ReadError.TRANSIENT to R.string.history_state_readerror_transient,
    ReadError.INVALID_RESPONSE to R.string.history_state_readerror_invalid_response,
    ReadError.BODY_TOO_LARGE to R.string.history_state_readerror_body_too_large,
    ReadError.CANCELLED to R.string.history_state_readerror_cancelled,
    ReadError.DEADLINE_EXCEEDED to R.string.history_state_readerror_deadline_exceeded,
    ReadError.OPERATION_NOT_ALLOWED to R.string.history_state_readerror_operation_not_allowed,
    DistributionUnavailable.InvalidFact.DURATION to R.string.history_state_invalidfact_duration,
    DistributionUnavailable.InvalidFact.RESET to R.string.history_state_invalidfact_reset,
    DistributionUnavailable.InvalidFact.IDENTITY to R.string.history_state_invalidfact_identity,
    DistributionUnavailable.InvalidFact.PERCENT to R.string.history_state_invalidfact_percent,
    DistributionUnavailable.InvalidFact.DECIMAL_CAPACITY to R.string.history_state_invalidfact_decimal_capacity,
)
